variables:
  HUB_ADDRESS: elmdockerhub:5000/grafana

image: docker:20.10.16

stages:
  - build
  - deploy
  - cleanup

services:
  - docker:20.10.16-dind 

before_script:
  - docker info

build-docker:
  tags: 
    - docker
  stage: build
  script:
    - docker build -t $HUB_ADDRESS:$CI_PIPELINE_ID .
    - docker images

push-image:
  tags:
    - docker
  stage: deploy
  script:
    - docker push $HUB_ADDRESS:$CI_PIPELINE_ID

cleanup:
  tags:
    - docker
  stage: cleanup
  script:
    - docker rmi $HUB_ADDRESS:$CI_PIPELINE_ID
  when: always
