variables:
  HUB_ADDRESS: elmdockerhub:5000/grafana

image: docker:20.10.16

stages:
  - build
  - deploy
  - cleanup

services:
  - docker:20.10.16-dind 

before_script:
  - docker info

build-docker:
  tags: 
    - docker
  stage: build
  script:
    - docker build -t $HUB_ADDRESS:$CI_PIPELINE_ID .
    - docker images | grep $HUB_ADDRESS

push-image:
  tags:
    - docker
  stage: deploy
  script:
    - docker push $HUB_ADDRESS:$CI_PIPELINE_ID

push-tag:
  only:
    - tags
  tags:
    - docker
  stage: deploy
  script:
    - docker image tag $HUB_ADDRESS:$CI_PIPELINE_ID $HUB_ADDRESS:$CI_COMMIT_TAG
    - docker push $HUB_ADDRESS:$CI_COMMIT_TAG
    - docker images | grep $HUB_ADDRESS
    - docker rmi $HUB_ADDRESS:$CI_COMMIT_TAG

cleanup:
  tags:
    - docker
  stage: cleanup
  script:
    - docker rmi $HUB_ADDRESS:$CI_PIPELINE_ID
  when: always
