variables:
  HUB_ADDRESS: dockerhub.elmatic-xenon.de/grafana

stages:
  - build
  - publish
  - cleanup
  - deploy

build-docker:
  tags: 
    - docker
  stage: build
  script:
    - ./xenon-build.sh
    - docker images | grep $HUB_ADDRESS

push-image:
  tags:
    - docker
  stage: publish
  script:
    - docker push $HUB_ADDRESS:$CI_PIPELINE_ID

push-tag:
  only:
    - tags
  tags:
    - docker
  stage: publish
  script:
    - docker image tag $HUB_ADDRESS:$CI_PIPELINE_ID $HUB_ADDRESS:$CI_COMMIT_TAG
    - docker push $HUB_ADDRESS:$CI_COMMIT_TAG
    - docker image tag $HUB_ADDRESS:$CI_PIPELINE_ID $HUB_ADDRESS:production
    - docker push $HUB_ADDRESS:production

    - docker images | grep $HUB_ADDRESS

    - docker rmi $HUB_ADDRESS:$CI_COMMIT_TAG
    - docker rmi $HUB_ADDRESS:production

push-main:
  only:
    - main
  tags:
    - docker
  stage: publish
  script:
    - docker image tag $HUB_ADDRESS:$CI_PIPELINE_ID $HUB_ADDRESS:$CI_COMMIT_REF_NAME
    - docker push $HUB_ADDRESS:$CI_COMMIT_REF_NAME
    - docker image tag $HUB_ADDRESS:$CI_PIPELINE_ID $HUB_ADDRESS:latest
    - docker push $HUB_ADDRESS:latest
    - docker image tag $HUB_ADDRESS:$CI_PIPELINE_ID $HUB_ADDRESS:staging
    - docker push $HUB_ADDRESS:staging

    - docker images | grep $HUB_ADDRESS

    - docker rmi $HUB_ADDRESS:$CI_COMMIT_REF_NAME
    - docker rmi $HUB_ADDRESS:latest
    - docker rmi $HUB_ADDRESS:staging

cleanup:
  tags:
    - docker
  stage: cleanup
  script:
    - docker rmi $HUB_ADDRESS:$CI_PIPELINE_ID
  when: always

deploy:
  stage: deploy
  only:
    - tags
    - main
  trigger:
    project: external/swarm/grafana-stack/grafana

deploy-testserver:
  stage: deploy
  when: manual
  tags:
    - docker
  image: 
    dockerhub.elmatic-xenon.de/ssh-client:production
  variables:
    SSH_PRECONFIG: testserver
  script:
    - ssh $SSH_PRECONFIG [[ -f /home/elmdocker/swarm/grafana.yaml ]] && echo "File already exists, no overwrite" || (echo "swarm-stack-testserver.yaml is missing on testserver. Please run main project pipeline for testserver first." && exit 1)
    - "ssh $SSH_PRECONFIG \"sed -i 's/\\(.*image: dockerhub\\.elmatic-xenon\\.de\\/grafana:\\).*/\\1'${CI_PIPELINE_ID}'/g' /home/elmdocker/swarm/grafana.yaml\""
    - ssh $SSH_PRECONFIG docker stack deploy --compose-file=/home/elmdocker/swarm/grafana.yaml grafana