version: '3.8'
services:
  grafana:
    build: .
    #image: dockerhub.elmatic-xenon.de/grafana:519
    #image: local:555
    hostname: grafana
    environment:
      GF_FEATURE_TOGGLES_ENABLE: internationalization
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,marcuscalidus-svg-panel,marcusolsson-csv-datasource, cloudspout-button-panel, agenty-flowcharting-panel"
      GF_SERVER_DOMAIN: localhost
      GF_SERVER_HTTP_PORT: 3001
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/"

      # OAuth
      # OAuth authentication
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "Xenon"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "5ieHCCvqP9E8loHGWbRCaEWoL62jWXWD"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://cloud.elmatic-align.de/realms/Xenon/protocol/openid-connect/auth
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://cloud.elmatic-align.de/realms/Xenon/protocol/openid-connect/token
      GF_AUTH_GENERIC_OAUTH_API_URL: https://cloud.elmatic-align.de/realms/Xenon/protocol/openid-connect/userinfo
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_SIGNOUT_REDIRECT_URL: https://cloud.elmatic-align.de/realms/Xenon/protocol/openid-connect/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&client_id=Xenon
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: "true"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "email"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(roles[*], 'admin') && 'GrafanaAdmin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'"
      # needed for orgrole sync. thats the json path to the attribute containing the orgrole list
      GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: "allowed_organizations"
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
      # has to be true to enable role updating from keycloak!
      GF_AUTH_OAUTH_SKIP_ORG_ROLE_UPDATE_SYNC: "true"
      GF_AUTH_LOGIN_COOKIE_NAME: "xenon_session"
      # fix problem with login when updating from Grafana 9.x.x to 10.x.x
      # see https://github.com/grafana/grafana/issues/70203#issuecomment-1609850174 for details
      # This might can be deleted once we upgraded successfuly
      GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP: "true"


      # date formats
      GF_DATE_FORMATS_FULL_DATE: "DD.MM.YYYY HH:mm:ss"
      GF_DATE_FORMATS_INTERVAL_DAY: "DD.MM"
      GF_DATE_FORMATS_INTERVAL_HOUR: "DD.MM HH:mm"
      GF_DATE_FORMATS_INTERVAL_MINUTE: "HH:mm"
      GF_DATE_FORMATS_INTERVAL_MONTH: "YYYY:MM"
      GF_DATE_FORMATS_INTERVAL_SECOND: "HH:mm:ss"
      GF_DATE_FORMATS_INTERVAL_YEAR: "YYYY"
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: "true" # Caution: This is still an experimental feature

      # language settings
      GF_USERS_DEFAULT_LANGUAGE: "de-DE"

      # EMail settings
      GF_EMAILS_WELCOME_EMAIL_ON_SIGN_UP: "false"
      GF_EMAILS_TEMPLATES_PATTERN: "emails/*.html, emails/*.txt"
      GF_EMAILS_CONTENT_TYPES: "text/html"

      # analytics
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"

      # snapshots
      GF_SNAPSHOTS_EXTERNAL_ENABLED: "false"

      # disable explorer
      GF_EXPLORE_ENABLED: "false"

      # panels settings
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"

      # image renderer
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000

      # debugging / logging
      GF_LOG_LEVEL: "debug"
      GF_LOG.CONSOLE_LEVEL: "debug"
    ports:
      - 3000:3001
    links:
      - grafana-renderer
    volumes:
      - grafana_data:/var/lib/grafana

  grafana-renderer:
    image: grafana/grafana-image-renderer:3.6.4
    hostname: grafana-renderer

volumes:
  grafana_data: